# Generated by Django 2.1.7 on 2019-04-08 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 8, 19, 3, 59, 591070), verbose_name='date published'),
        ),
    ]
